name: Chess Server CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Project Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: chess
          POSTGRES_PASSWORD: chess
          POSTGRES_DB: chess_test
        ports:
          - 5432:5432

    env:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: chess
      DB_PASSWORD: chess
      DB_NAME: chess_test
      DB_SSLMODE: disable

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: "1.25"

      - name: Download Dependencies
        run: go mod download

      - name: Run Tests
        run: go test ./...