name: Chess Server CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Project Tests
    runs-on: ubuntu-latest

    steps:
      - name: System Runner
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7

        with:
          go-version: "1.25"

      - name: Download Dependencies
        run: go mod download

      - name: Run Tests
        run: go test ./..
